language: go

services:
  - postgresql

install:
  - go get github.com/astaxie/beego
  - go get github.com/beego/bee

  before_script:
    - psql -c 'create database hanuman_dev;' -U postgres
    - psql -c 'create user hanuman with password \'123456\';' -U postgres
    - psql -c 'GRANT ALL PRIVILEGES ON DATABASE hanuman_dev to hanuman;' -U postgres

    